### ISSUE TITLE
ACF Pro doesn't see the key from a environment variable

### ISSUE THREAD

**Issue by certainlyakey** [PhilippBaschke/acf-pro-installer#10]
First of all, thanks for all the work done with this plugin. I've got one question related to how it works though.

I installed ACF Pro via Composer with the Installer plugin, but somehow ACF Pro doesn't see the Pro serial number in an env variable. I checked if the variable is there with PHP command `get_defined_vars()` and I see `ACF_PRO_KEY ` there (in the `_SERVER` section of the printed array). 

However, the key is not accepted (or read) when the plugin's installed, so that I still see the box with the empty license information in the ACF's Custom fields->Updates section: http://take.ms/6eFuZ. Is it supposed to be like this and the installer plugin just uses the provided key to allow for downloading the ACF Pro or it should apply that key to unlock the updates as well?

**Comment by PhilippBaschke** [comment]
Thank you for your question and sorry for the late answer ☺️ 

The plugin is just meant to be used with composer and does **not** modify anything in WordPress. I think the general idea when using composer with WordPress is to *never* use the WordPress auto update functionality and update WordPress, plugins and themes via composer.

You should be able to update ACF PRO with the following procedure:

1. Change the `version` in the `repositories` section to the desired version (see [Usage (Step 1)](https://github.com/PhilippBaschke/acf-pro-installer#usage))

2. Run `composer update`

I hope that answers your question. Let me know if you have further questions. I am happy to help ☺️

**Comment by certainlyakey** [comment]
Hi Philipp! 
Thanks for your reply. 
To be exact it's not about updating, it's about automated installing ACF Pro in different environments (for example, on various locals and on staging), but I get your point — the installer isn't supposed to apply a key to the installation, we put the key into an `.env` file or as a env variable to allow for downloading plugin from ACF server only, and it should be pasted then manually in a Wordpress admin to be applied. But as the key in Wordpress only enables updates via admin maybe it's not even needed as we want them to be initiated only from composer.
Consider this issue resolved then, and thanks :)
