### ISSUE TITLE
HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by rolandp** [PhilippBaschke/acf-pro-installer#11]
I have a similar issue as described in issue #5. 

I've added the following code to the composer.json file that's in the root of my theme

`  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "advanced-custom-fields/advanced-custom-fields-pro",
        "version": "5.3.10",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://connect.advancedcustomfields.com/index.php?p=pro&a=download"
        },
        "require": {
          "philippbaschke/acf-pro-installer": "^1.0",
          "composer/installers": "^1.0"
        }
      }
    }
  ],`

I then added the ACF_PRO_KEY variable (with key) to the .env file. 

Then when I run the command `composer require advanced-custom-fields/advanced-custom-fields-pro:*`, I get the following error message:
`[Composer\Downloader\TransportException]
The 'https://connect.advancedcustomfields.com/index.php?p=pro&a=download&t=5.3.10&k=b3jk...' URL could not be accessed: HTTP/1.1 400 Bad Request`

My composer version is:
`composer --version
Composer version 1.4-dev 2017-01-22 19:01:35`

When checking the url (with and without the GET params) in Chrome's Postman I get the same `400 Bad Request` error.

What is causing this issue and how can I fix this?

**Comment by PhilippBaschke** [comment]
Sorry for the late answer. I did not see the issue. 😞 

Did you double check your key? I used the URL that you posted `https://connect.advancedcustomfields.com/index.php?p=pro&a=download&t=5.3.10&k=WRONG_KEY` and got a `400` as well (just tested it in the Browser). However, when I replace `WRONG_KEY` with my key, the download works just fine. 😕

**Comment by mickaelzhang** [comment]
I'm running into this problem as well on my mac and also on my server. 
The issue seems to be that composer install try to install `advanced-custom-fields/advanced-custom-fields-pro` first and then `acf-pro-installer`.

**Comment by PhilippBaschke** [comment]
@mickaelzhang Can you post the (relvant) contents of your `composer.json`? Because when you specify that ACF requires `acf-pro-installer` it should be installed before. I also think it is not the case for @rolandp because the URL in the error message contains a `version` and `key` parameter which gets added by `acf-pro-installer`. 😕

**Comment by rolandp** [comment]
@PhilippBaschke Thanks for getting back to me and pointing me in the direction of the key. I think the problem was a space before the actual key in my .env file. I've got it working now without changing anything else.

Would it be possible to return a difference error code for an invalid key? Something like a 403?

**Comment by PhilippBaschke** [comment]
I'm glad that your Problem was solved. The better error code is good suggestion 😌 However, the error code comes from ACF directly and I can't really influence it 😞

**Comment by slackday** [comment]
I'm using `acf-pro-installer` on several projects and it's great thanks! However on one project I'm getting this error all of a sudden and configuration is the same on projects that work and this that don't work... I'm out of ideas... any suggestions what to troubleshoot? 🤔

**Comment by PhilippBaschke** [comment]
Glad that you like it @slackday. 😌  Did you double check your key? It would be really helpful if you could share your `composer.json` file. ☺️

**Comment by slackday** [comment]
Thanks for you answer, sorry I missed it by a week didn't see the notification.

Here is my `composer.json` file https://gist.github.com/slackday/1f25e7cd73de3f5e4d0795f1b2916f44

**Comment by PhilippBaschke** [comment]
Hey @slackday.
Thank you for your `composer.json` file. When I run `composer install` with your `composer.json` and my `ACF_PRO_KEY` everything works as expected (like it does on all your other projects).

Have you tried opening the URL that the error message returns in the Browser?
```
[Composer\Downloader\TransportException]                                                                                                          
The 'https://connect.advancedcustomfields.com/index.php?p=pro&a=download&t=5.5.11&k=WRONG_KEY' URL could not be accessed: HTTP/1.1 400 Bad Request
```

You could also try to copy the key and compare it letter by letter with [your key](https://www.advancedcustomfields.com/my-account/).

**Comment by slackday** [comment]
The url from the error message doesn't contain a key. It tries to access same URL as in the composer.json. I have the key in `.env` on server but in this case it doesn't get added same way as on other servers/localhost.

**Comment by PhilippBaschke** [comment]
That is super strange 😱 Would you mind running clearing the composer files, installing again and then show me the console output of the install step?

In your project directory
```
$ rm composer.lock
$ rm -rf vendor
$ composer clearcache
$ composer install
```

**Comment by slackday** [comment]
Super strange yes. I only had this problem on server when running deploy. 

I ran the deploy again to get the composer error message for you but I ran into other issues with the deploy.

I upgraded `wp-cli` from `v0.24.1` to `v1.1.0` to fix the issue with the deploy and ran it again. Successfully. And the ACF key was added aswell.

My issue on this server seems to be resolved. Thanks for all your help and taking you time with this.

**Comment by codilechasseur** [comment]
For anyone having issues right now with this. It looks like ACF has broken the "t=" part of their download URL. Tested from composer, browser and from the account dashboard of ACF's site. 

**BROKEN**
https://connect.advancedcustomfields.com/index.php?p=pro&a=download&k={ACF_PRO_KEY}&t=5.5.14

**WORKS**
https://connect.advancedcustomfields.com/index.php?p=pro&a=download&k={ACF_PRO_KEY}

**Comment by timalbert** [comment]
I am having this same problem. Any thoughts on how to fix? @PhilippBaschke can we remove the "&t=xxx" from the installer plugin.

**Comment by codilechasseur** [comment]
I reached out to ACF and they've fixed the problem on their end. @timalbert can you try again? Perhaps try clearing you composer cache first?

**Comment by PhilippBaschke** [comment]
Awesome @codilechasseur! Thank you so much for your effort! ☺️

**Comment by timalbert** [comment]
Hey @codilechasseur and @PhilippBaschke - I am still getting the same error even with composer cache cleared. Just performed a test and it fails with the `t=5.3.9` parameter, but downloads as expected when removed. Have you been able to get this working successfully?

**Comment by PSahner** [comment]
I also can not download because of a string conversion problem. My ACF Pro key has an is equal sign ('=') as last character. On my Mac it is working fine but on my linux server it gets transformed to '%3D'. How can I fix this issue?

**Comment by PhilippBaschke** [comment]
@timalbert Sorry for the very late answer. I did not have time to try it until now but as you can see in the ACF versions lists ([My Account](https://www.advancedcustomfields.com/my-account/) > See all versions) `5.3.9` is not available. I guess you have to install a different version. ☺️ 

@PSahner Can you paste the error output here? That might help to find where the problem could come from. Thank you! 😌 The encoding is probably from [here](https://github.com/PhilippBaschke/acf-pro-installer/blob/master/src/ACFProInstaller/Plugin.php#L267) but I can't think of a reason why there should be difference between Linux and macOS. 😕

**Comment by PSahner** [comment]
This is the error I get:
```
Installing advanced-custom-fields/advanced-custom-fields-pro (5.5.1.4): Downloading [Composer\Downloader\TransportException] The 'https://connect.advancedcustomf
ields.com/index.php?p=pro&a=download&t=5.5.1.4&k=[THE_KEY]' URL could not be accessed: HTTP/1.1 400 Bad Request
```
And the string for the key has a `%3D` instead of `=` at the end. So when I copy and paste the URL in my browser it does not work. But when I change the `%3D` to `=` manually it works.
I guess the `urlencode($value)` part is responsible for that problem where it changes the `=` character to hex code?

**Comment by PhilippBaschke** [comment]
I opened a ticket at ACF. Maybe they have an idea what to do about it ☺️

**Comment by cupojoe** [comment]
Any movement on this?
