### ISSUE TITLE
Error on Deploy only: Could not find a key for ACF PRO. Please make it available via the environment variable ACF_PRO_KEY install

### ISSUE THREAD

**Issue by s3w47m88** [PhilippBaschke/acf-pro-installer#14]
Hey Philipp,

I tried deploying my first Trellis + Bedrock + Sage setup to `staging` today and got this error and I'm not sure what to do about it:

`TASK [deploy : Install Composer dependencies] **********************************
System info:
  Ansible 2.2.1.0; Darwin
  Trellis at "Check Ansible version before Ansible validates task attributes"
---------------------------------------------------
Loading composer repositories with package information Installing
dependencies from lock file Package operations: 14 installs, 0 updates, 0
removals - Installing composer/installers (v1.0.25): Loading from cache -
Installing johnpbloch/wordpress-core-installer (0.2.1): Loading from cache -
Installing vlucas/phpdotenv (v2.4.0): Loading from cache - Installing
philippbaschke/acf-pro-installer (v1.0.2): Loading from cache - Installing
advanced-custom-fields/advanced-custom-fields-pro (5.5.11):
[PhilippBaschke\ACFProInstaller\Exceptions\MissingKeyException] Could not
find a key for ACF PRO. Please make it available via the environment variable
ACF_PRO_KEY install [--prefer-source] [--prefer-dist] [--dry-run] [--dev]
[--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-
progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a
|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--]
[<packages>]...
fatal: [staging.kangapestcontrol.com]: FAILED! => {"changed": false, "failed": true, "stdout": "Loading composer repositories with package information\nInstalling dependencies from lock file\nPackage operations: 14 installs, 0 updates, 0 removals\n  - Installing composer/installers (v1.0.25): Loading from cache\n  - Installing johnpbloch/wordpress-core-installer (0.2.1): Loading from cache\n  - Installing vlucas/phpdotenv (v2.4.0): Loading from cache\n  - Installing philippbaschke/acf-pro-installer (v1.0.2): Loading from cache\n  - Installing advanced-custom-fields/advanced-custom-fields-pro (5.5.11): \n                                                                                                       \n  [PhilippBaschke\\ACFProInstaller\\Exceptions\\MissingKeyException]                                      \n  Could not find a key for ACF PRO. Please make it available via the environment variable ACF_PRO_KEY  \n                                                                                                       \n\ninstall [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...\n\n", "stdout_lines": ["Loading composer repositories with package information", "Installing dependencies from lock file", "Package operations: 14 installs, 0 updates, 0 removals", "  - Installing composer/installers (v1.0.25): Loading from cache", "  - Installing johnpbloch/wordpress-core-installer (0.2.1): Loading from cache", "  - Installing vlucas/phpdotenv (v2.4.0): Loading from cache", "  - Installing philippbaschke/acf-pro-installer (v1.0.2): Loading from cache", "  - Installing advanced-custom-fields/advanced-custom-fields-pro (5.5.11): ", "                                                                                                       ", "  [PhilippBaschke\\ACFProInstaller\\Exceptions\\MissingKeyException]                                      ", "  Could not find a key for ACF PRO. Please make it available via the environment variable ACF_PRO_KEY  ", "                                                                                                       ", "", "install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...", ""]}
	to retry, use: --limit @/Users/spencerhill/Sites/kangapestcontrol.com/trellis/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0
staging.kangapestcontrol.com : ok=14   changed=4    unreachable=0    failed=1`

I **do** have my ACF Pro key in my .env file locally and it's working locally just fine.

**Comment by PhilippBaschke** [comment]
I never used Trellis before so I am not an expert. But I think your server can't use the `.env` file on your machine.

Did you add `acf_pro_key` to the [`vault.yml`](https://roots.io/trellis/docs/wordpress-sites/#passwordssecrets) file of your staging environment? MWDelaney posted an example on the [Roots.io forum](https://discourse.roots.io/t/acf-pro-as-a-composer-dependency-without-committing-your-license-key/6690).

Please let me know if that helps. You might consider opening a question in the Roots.io forum to get help. 😌

**Comment by s3w47m88** [comment]
Thanks for the reply Philipp. That post from MWDelaney solved the issue for me!
