### ISSUE TITLE
Fatal error: Class 'Dotenv\Dotenv' not found in ACFProInstaller/Plugin.php

### ISSUE THREAD

**Issue by maciekpaprocki** [PhilippBaschke/acf-pro-installer#17]
I am not sure why would that happen, but it does. I used this installer few good times now and only on this one set up it seems to make some problems. 

Full log:
Fatal error: Class 'Dotenv\Dotenv' not found in /var/www/***/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php on line 246
PHP Fatal error:  Class 'Dotenv\Dotenv' not found in /var/www/***/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php on line 246

I had been previously using dotenv:1.* without acf installer and now when I am trying to  use installer and updated version of dotenv it throws this error. 

Any ideas?

By the way, Thank you very much for the this extension. It definitely makes my life easier.

**Comment by PhilippBaschke** [comment]
Thank you for your report @maciekpaprocki and thank you for your kind words ☺️ 

That is very strange. 😕 Did you try rerunning `composer install`? Would you mind sharing your `composer.json` (feel free to only share the relevant parts)? Thank you 😌

**Comment by maciekpaprocki** [comment]
Hmm, sorry for late answer. I completely missed that. 

I think the issue was caused by me trying to use installer at this same time as updating dotenv. As your  installer requires dotenv v2 and was running first it was failing. I am not sure what I did and it's hard to reproduce that, but solution is to upgrade dotenv first and then your installer. 

I am closing the issue, thanks for installer and quick answer and sorry for late reply.

**Comment by regenrek** [comment]
I think this bug is still relevant!

It doesn't happen everytime but currently I'm stuck on this problem.
Here are my files (in short):


```
{
repositories: {
        "acf-pro": {
            "type": "package",
            "package": {
                "name": "advanced-custom-fields/advanced-custom-fields-pro",
                "type": "wordpress-plugin",
                "version" :"5.6.0",
                "dist": {
                  "type": "zip",
                  "url": "https://connect.advancedcustomfields.com/index.php?p=pro&a=download"
                },
                "require": {
                  "philippbaschke/acf-pro-installer": "^1.0",
                  "composer/installers": "^1.0"
                }
            }
        },
     }
    "require": {
        "php": "^7.0",
        "composer/installers": "~1.0",
        "oscarotero/env": "^1.0",
        "vlucas/phpdotenv": "^2.4",
        "symfony/var-dumper": "^3.3",
        "advanced-custom-fields/advanced-custom-fields-pro":"^6.5.0"
 }
}
```

My Command: (via Capistrano Deploy)

```php composer.phar install --working-dir #{release_path} --no-dev --prefer-dist --no-interaction --optimize-autoloader --no-scripts```

Output:

```
/usr/local/bin/php7-70STABLE-CLI /kunden/495732_2870//rp-hosting/22/49/shared/composer.phar install --working-dir /kunden/495732_2870//rp-hosting/22/49/releases/20171003092509 --no-dev --prefer-dist --no-interaction --optimize-autoloader --no-scripts stdout: Fatal error: Uncaught Error: Class 'Dotenv\Dotenv' not found in /kunden/495732_2870/rp-hosting/22/49/releases/20171003092509/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php:246
Stack trace:
#0 /kunden/495732_2870/rp-hosting/22/49/releases/20171003092509/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php(226): PhilippBaschke\ACFProInstaller\Plugin->loadDotEnv()
#1 /kunden/495732_2870/rp-hosting/22/49/releases/20171003092509/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php(144): PhilippBaschke\ACFProInstaller\Plugin->getKeyFromEnv()
#2 [internal function]: PhilippBaschke\ACFProInstaller\Plugin->addKey(Object(Composer\Plugin\PreFileDownloadEvent))
#3 phar:///kunden/495732_2870/rp-hosting/22/49/shared/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Plugin\PreFileDownloadEvent))
#4 phar:///kunden/495732_2870/rp-hosting/22/49/shared/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(81): Compos in /kunden/495732_2870/rp-hosting/22/49/releases/20171003092509/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php on line 246
/usr/local/bin/php7-70STABLE-CLI /kunden/495732_2870//rp-hosting/22/49/shared/composer.phar install --working-dir /kunden/495732_2870//rp-hosting/22/49/releases/20171003092509 --no-dev --prefer-dist --no-interaction --optimize-autoloader --no-scripts stderr: Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
```
