### ISSUE TITLE
Version restricted to 3 digits

### ISSUE THREAD

**Issue by igniteonline** [PhilippBaschke/acf-pro-installer#2]
when calling `validateVersion` the installer expects exactly 3 digits, although ACF also releases updates with 4 digits as of version 5.3.8.1.
The regular expression to match against should be 
` $major_minor_patch = '/\A\d\.\d\.\d(\.\d)?\Z/';`

**Comment by PhilippBaschke** [comment]
Good catch! I'll work on it. :relaxed:
