### ISSUE TITLE
Cannot install ACF Pro 5.3.10

### ISSUE THREAD

**Issue by jamiechong** [PhilippBaschke/acf-pro-installer#4]
The composer install fails with this error. 
`[UnexpectedValueException]                                                                                                                         
  The version constraint of advanced-custom-fields/advanced-custom-fields-pro should be exact (with 3 or 4 digits). Invalid version string "5.3.10" `

The problem looks to be an issue with your regex one Line 187 of Plugin.php

**Comment by PhilippBaschke** [comment]
Thank you @jamiechong. Fix is on the way 😊

**Comment by Rhymes2k** [comment]
Same Error still occurs with pre-release versions e.g. "5.4.0-RC1". Or is there another way to require stable-tags? see https://getcomposer.org/doc/04-schema.md#version

**Comment by PhilippBaschke** [comment]
@Rhymes2k Good call. I will add the RC part. 

What do you mean by "other way to require stable-tags"? Do you think I should allow all versions that are allowed according to Composer? But it seems like that 5.3.9.1 is not allowed by Composer (but ACF might use it).

**Comment by Rhymes2k** [comment]
As far as I know ACF sticks 3 digit versioning - at least since v5. 
Would it harm to ease the restrictions (or even remove them)? Wouldn't composer just complain about the package url not being reachable if the version doesnt exist?
I can't think of any perfect solution here until Elliot adds composer support to acf pro himself.

**Comment by PhilippBaschke** [comment]
@Rhymes2k I'll investigate the composer error messages. If they are fairly explanatory, I'll consider removing the constraint alltogether. It seems a little to brittle (I got surprised by new versions twice now). 😕
