### ISSUE TITLE
Error 400: Bad Request

### ISSUE THREAD

**Issue by tyrann0us** [PhilippBaschke/acf-pro-installer#5]
When trying to install (latest) version of ACF composer fails with error message

`[Composer\Downloader\TransportException]
The 'https://connect.advancedcustomfields.com/index.php?p=pro&a=download' URL could not be accessed: HTTP/1.1 400 Bad Request`

Trying to manually download the zip file using the browser (with `?k={ACF_PRO_KEY}`) seems to work in 2 of 10 attempts.

Is there anything that can be done on the plugin side?
Thanks!

**Comment by PhilippBaschke** [comment]
Thank you for your report @tyrann0us.
I could not reproduce the error with the following `composer.json`:

```json
{
  "name": "test",
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "advanced-custom-fields/advanced-custom-fields-pro",
        "version": "5.3.10",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://connect.advancedcustomfields.com/index.php?p=pro&a=download"
        },
        "require": {
          "philippbaschke/acf-pro-installer": "^1.0",
          "composer/installers": "^1.0"
        }
      }
    }
  ]
}
```
and the following `.env` file:
```
ACF_PRO_KEY={ACF_PRO_KEY}
```

I ran the following commands:
```shell
composer clearcache
composer require advanced-custom-fields/advanced-custom-fields-pro:*
```
My composer version is:
```
composer --version
Composer version 1.2.0 2016-07-19 01:28:52
```

Can you try this with your key and see if you still get a `400` error? It would be nice if you could tell me the exact steps that lead to the `400` error on your machine. Maybe I can reproduce the error then. 😊

**Comment by tyrann0us** [comment]
This is totally my fault.
I added the `"require" : {}` part to the general `require` section of my `composer.json` instead having it inside the ACF's `package:{}` section.
Sorry for the trouble! And keep up the good work!

**Comment by PhilippBaschke** [comment]
Thank you! Don't worry, glad to help! :blush:
