### ISSUE TITLE
composer require returns error: invalid package definition

### ISSUE THREAD

**Issue by JKirchartz** [PhilippBaschke/acf-pro-installer#6]
I'm using composer 1.2.0, and I've copy/pasted the repository to my composer.json as described in the readme file, but when I try to install with `composer require advanced-custom-fields/advanced-custom-fields-pro:*` (also from the readme) I get this error message:

```
[Composer\Repository\InvalidRepositoryException]
  A repository of type "package" contains an invalid package definition: Invalid package information:
  version : invalid value (*.*.*(.*)): Invalid version string "*.*.*(.*)"
  Invalid package definition:
  {"name":"advanced-custom-fields\/advanced-custom-fields-pro","version":"*.*.*(.*)","type":"wordpress-plugin","dist":{"type":"zip","url":"https:\/\/connect.advancedcustomfields.com\/index.php?p=pro&a=download"},"require":{"philippbaschke\/acf-pro-installer":"^1.0","co
  mposer\/installers":"^1.0"}}
```

I tried removing the version string, but then I get an error message saying `Package advanced-custom-fields/advanced-custom-fields-pro has no version defined.`

I'm new to composer (and just getting back into PHP) so I'm not really sure how to work around this issue.

**Comment by PhilippBaschke** [comment]
Thank you for your issue report @JKirchartz.

Did you replace the version placeholder `*.*.*(.*)` with an actual version (e.g. `5.4.2`)?

```diff
{
  "type": "package",
  "package": {
    "name": "advanced-custom-fields/advanced-custom-fields-pro",
-    "version": "*.*.*(.*)",
+    "version": "5.4.2",
    "type": "wordpress-plugin",
    "dist": {
      "type": "zip",
      "url": "https://connect.advancedcustomfields.com/index.php?p=pro&a=download"
    },
    "require": {
      "philippbaschke/acf-pro-installer": "^1.0",
      "composer/installers": "^1.0"
    }
  }
}
```

**Comment by JKirchartz** [comment]
That seems to have been the issue, it wanted the actual number.
